# Etapa 1: Build de la aplicación
FROM maven:3.9.11 AS build

# Crear directorio base
WORKDIR /app

# Copiar todos los módulos del proyecto multi-módulo
COPY ./back_common ./back_common
COPY ./back_streaming ./back_streaming
COPY ./pom.xml ./

# Instalar el POM padre para que los módulos puedan encontrarlo
RUN mvn -f pom.xml install -N

WORKDIR /app/back_common
# Compilar el microservicio
RUN mvn clean install -DskipTests

WORKDIR /app/back_streaming
RUN mvn clean package -DskipTests

# Etapa 2: Imagen final con solo el JAR
FROM eclipse-temurin:21-jdk

WORKDIR /app

# Copiar el JAR compilado desde el build
COPY --from=build /app/back_streaming/target/*.jar app.jar

# Instalar FFmpeg
RUN apt update && apt upgrade -y && apt install ffmpeg -y && rm -rf /var/lib/apt/lists/*

EXPOSE 8070

ENTRYPOINT ["java", "-jar", "app.jar"]