services:
    sovschool-front:
        image: sovschool-front
        build:
            context: ../front
            dockerfile: Dockerfile
        container_name: sovschool-front
        env_file:
            - ../front/.env
        ports:
            - "${FRONT_PORT}:4200"
        volumes:
            - /etc/letsencrypt/live/giacca90.ddns.net/cert.pem:/certs/cert.pem:ro
            - /etc/letsencrypt/live/giacca90.ddns.net/privkey.pem:/certs/key.pem:ro

        networks:
            - sovschool-network
        depends_on:
            - sovschool-back-base
            - sovschool-back-chat
            - sovschool-back-stream
            - sovschool-rtmp

    sovschool-postgres:
        image: sovschool-postgres
        build:
            context: .
            dockerfile: Dockerfile.postgres
        container_name: sovschool-postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        networks:
            - sovschool-network
        volumes:
            - sovschool-postgres:/var/lib/postgresql/data

    sovschool-mongo:
        image: sovschool-mongo
        build:
            context: .
            dockerfile: Dockerfile.mongo
        container_name: sovschool-mongo
        ports:
            - "${MONGO_PORT}:27017"

        command: ["mongod", "--replSet", "rs0", "--quiet", "--setParameter", "logLevel=0"]

        #command: ["mongod"]
        networks:
            - sovschool-network
        volumes:
            - sovschool-mongo-data:/data/db
            - sovschool-mongo-config:/data/configdb

    sovschool-rtmp:
        image: sovschool-rtmp
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: sovschool-rtmp
        ports:
            - "${RTMP_PORT}:8060"
        networks:
            - sovschool-network

    sovschool-back-base:
        image: sovschool-back-base
        build:
            context: .
            dockerfile: Dockerfile.back_base
        container_name: sovschool-back-base
        env_file:
            - .env.back_base
        ports:
            - "${BACK_BASE_PORT}:8080"
        networks:
            - sovschool-network
        volumes:
            - sovschool-fotos:/Fotos
            - sovschool-videos:/Videos
            - /etc/letsencrypt/live/giacca90.ddns.net/keystore.p12:/certs/keystore.p12:ro
        depends_on:
            - sovschool-postgres
            - sovschool-mongo

    sovschool-back-chat:
        image: sovschool-back-chat
        build:
            context: .
            dockerfile: Dockerfile.back_chat
        container_name: sovschool-back-chat
        env_file:
            - .env.back_chat
        ports:
            - "${BACK_CHAT_PORT}:8070"
        networks:
            - sovschool-network
        volumes:
            - /etc/letsencrypt/live/giacca90.ddns.net/keystore.p12:/certs/keystore.p12:ro
        depends_on:
            - sovschool-postgres
            - sovschool-mongo

    sovschool-back-stream:
        image: sovschool-back-stream
        build:
            context: .
            dockerfile: Dockerfile.back_stream
        container_name: sovschool-back-stream
        env_file:
            - .env.back_stream
        ports:
            - "${BACK_STREAM_PORT}:8090"
        networks:
            - sovschool-network
        volumes:
            - sovschool-videos:/Videos
            - /etc/letsencrypt/live/giacca90.ddns.net/keystore.p12:/certs/keystore.p12:ro
        depends_on:
            - sovschool-postgres
            - sovschool-mongo
            - sovschool-rtmp

networks:
    sovschool-network:
        name: sovschool-network
        driver: bridge

volumes:
    sovschool-fotos:
        name: sovschool-fotos
    sovschool-mongo-config:
        name: sovschool-mongo-config
    sovschool-mongo-data:
        name: sovschool-mongo-data
    sovschool-postgres:
        name: sovschool-postgres
    sovschool-videos:
        name: sovschool-videos
