# Etapa 1: Build de la aplicación
FROM maven:3.9.11 AS build

# Crear directorio base
WORKDIR /app

# Copiar todos los módulos del proyecto multi-módulo
COPY ./back_common ./back_common
COPY ./back_chat ./back_chat
COPY ./pom.xml ./

# Instalar el POM padre para que los módulos puedan encontrarlo
RUN mvn -f pom.xml install -N

WORKDIR /app/back_common
# Compilar el microservicio
RUN mvn clean install -DskipTests

WORKDIR /app/back_chat
RUN mvn clean package -DskipTests

# Etapa 2: Imagen final con solo el JAR
FROM eclipse-temurin:21-jdk

WORKDIR /app

RUN apt update && apt upgrade -y && rm -rf /var/lib/apt/lists/*

# Copiar el JAR compilado desde el build
COPY --from=build /app/back_chat/target/*.jar app.jar

EXPOSE 8070

ENTRYPOINT ["java", "-jar", "app.jar"]